/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthScheduleRouteImport } from './routes/_auth.schedule'
import { Route as AuthReportsRouteImport } from './routes/_auth.reports'
import { Route as AuthMaintenanceRouteImport } from './routes/_auth.maintenance'
import { Route as AuthInterventionsRouteImport } from './routes/_auth.interventions'
import { Route as AuthGseRouteImport } from './routes/_auth.gse'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthChecklistRouteImport } from './routes/_auth.checklist'
import { Route as AuthCarburantRouteImport } from './routes/_auth.carburant'
import { Route as AuthAttendanceRouteImport } from './routes/_auth.attendance'
import { Route as AuthAgentsRouteImport } from './routes/_auth.agents'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthScheduleRoute = AuthScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMaintenanceRoute = AuthMaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInterventionsRoute = AuthInterventionsRouteImport.update({
  id: '/interventions',
  path: '/interventions',
  getParentRoute: () => AuthRoute,
} as any)
const AuthGseRoute = AuthGseRouteImport.update({
  id: '/gse',
  path: '/gse',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthChecklistRoute = AuthChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCarburantRoute = AuthCarburantRouteImport.update({
  id: '/carburant',
  path: '/carburant',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAttendanceRoute = AuthAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAgentsRoute = AuthAgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agents': typeof AuthAgentsRoute
  '/attendance': typeof AuthAttendanceRoute
  '/carburant': typeof AuthCarburantRoute
  '/checklist': typeof AuthChecklistRoute
  '/dashboard': typeof AuthDashboardRoute
  '/gse': typeof AuthGseRoute
  '/interventions': typeof AuthInterventionsRoute
  '/maintenance': typeof AuthMaintenanceRoute
  '/reports': typeof AuthReportsRoute
  '/schedule': typeof AuthScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/agents': typeof AuthAgentsRoute
  '/attendance': typeof AuthAttendanceRoute
  '/carburant': typeof AuthCarburantRoute
  '/checklist': typeof AuthChecklistRoute
  '/dashboard': typeof AuthDashboardRoute
  '/gse': typeof AuthGseRoute
  '/interventions': typeof AuthInterventionsRoute
  '/maintenance': typeof AuthMaintenanceRoute
  '/reports': typeof AuthReportsRoute
  '/schedule': typeof AuthScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/agents': typeof AuthAgentsRoute
  '/_auth/attendance': typeof AuthAttendanceRoute
  '/_auth/carburant': typeof AuthCarburantRoute
  '/_auth/checklist': typeof AuthChecklistRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/gse': typeof AuthGseRoute
  '/_auth/interventions': typeof AuthInterventionsRoute
  '/_auth/maintenance': typeof AuthMaintenanceRoute
  '/_auth/reports': typeof AuthReportsRoute
  '/_auth/schedule': typeof AuthScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/agents'
    | '/attendance'
    | '/carburant'
    | '/checklist'
    | '/dashboard'
    | '/gse'
    | '/interventions'
    | '/maintenance'
    | '/reports'
    | '/schedule'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/agents'
    | '/attendance'
    | '/carburant'
    | '/checklist'
    | '/dashboard'
    | '/gse'
    | '/interventions'
    | '/maintenance'
    | '/reports'
    | '/schedule'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/agents'
    | '/_auth/attendance'
    | '/_auth/carburant'
    | '/_auth/checklist'
    | '/_auth/dashboard'
    | '/_auth/gse'
    | '/_auth/interventions'
    | '/_auth/maintenance'
    | '/_auth/reports'
    | '/_auth/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/schedule': {
      id: '/_auth/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthScheduleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/maintenance': {
      id: '/_auth/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof AuthMaintenanceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/interventions': {
      id: '/_auth/interventions'
      path: '/interventions'
      fullPath: '/interventions'
      preLoaderRoute: typeof AuthInterventionsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/gse': {
      id: '/_auth/gse'
      path: '/gse'
      fullPath: '/gse'
      preLoaderRoute: typeof AuthGseRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/checklist': {
      id: '/_auth/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof AuthChecklistRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/carburant': {
      id: '/_auth/carburant'
      path: '/carburant'
      fullPath: '/carburant'
      preLoaderRoute: typeof AuthCarburantRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/attendance': {
      id: '/_auth/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthAttendanceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/agents': {
      id: '/_auth/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AuthAgentsRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAgentsRoute: typeof AuthAgentsRoute
  AuthAttendanceRoute: typeof AuthAttendanceRoute
  AuthCarburantRoute: typeof AuthCarburantRoute
  AuthChecklistRoute: typeof AuthChecklistRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthGseRoute: typeof AuthGseRoute
  AuthInterventionsRoute: typeof AuthInterventionsRoute
  AuthMaintenanceRoute: typeof AuthMaintenanceRoute
  AuthReportsRoute: typeof AuthReportsRoute
  AuthScheduleRoute: typeof AuthScheduleRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAgentsRoute: AuthAgentsRoute,
  AuthAttendanceRoute: AuthAttendanceRoute,
  AuthCarburantRoute: AuthCarburantRoute,
  AuthChecklistRoute: AuthChecklistRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthGseRoute: AuthGseRoute,
  AuthInterventionsRoute: AuthInterventionsRoute,
  AuthMaintenanceRoute: AuthMaintenanceRoute,
  AuthReportsRoute: AuthReportsRoute,
  AuthScheduleRoute: AuthScheduleRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
