/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthUsersRouteImport } from './routes/_auth.users'
import { Route as AuthScheduleRouteImport } from './routes/_auth.schedule'
import { Route as AuthReportsRouteImport } from './routes/_auth.reports'
import { Route as AuthInstallationsRouteImport } from './routes/_auth.installations'
import { Route as AuthIncidentsRouteImport } from './routes/_auth.incidents'
import { Route as AuthForumRouteImport } from './routes/_auth.forum'
import { Route as AuthEquipmentRouteImport } from './routes/_auth.equipment'
import { Route as AuthDashboardRouteImport } from './routes/_auth.dashboard'
import { Route as AuthAttendanceRouteImport } from './routes/_auth.attendance'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthUsersRoute = AuthUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthRoute,
} as any)
const AuthScheduleRoute = AuthScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsRoute = AuthReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInstallationsRoute = AuthInstallationsRouteImport.update({
  id: '/installations',
  path: '/installations',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIncidentsRoute = AuthIncidentsRouteImport.update({
  id: '/incidents',
  path: '/incidents',
  getParentRoute: () => AuthRoute,
} as any)
const AuthForumRoute = AuthForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => AuthRoute,
} as any)
const AuthEquipmentRoute = AuthEquipmentRouteImport.update({
  id: '/equipment',
  path: '/equipment',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAttendanceRoute = AuthAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AuthAttendanceRoute
  '/dashboard': typeof AuthDashboardRoute
  '/equipment': typeof AuthEquipmentRoute
  '/forum': typeof AuthForumRoute
  '/incidents': typeof AuthIncidentsRoute
  '/installations': typeof AuthInstallationsRoute
  '/reports': typeof AuthReportsRoute
  '/schedule': typeof AuthScheduleRoute
  '/users': typeof AuthUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/attendance': typeof AuthAttendanceRoute
  '/dashboard': typeof AuthDashboardRoute
  '/equipment': typeof AuthEquipmentRoute
  '/forum': typeof AuthForumRoute
  '/incidents': typeof AuthIncidentsRoute
  '/installations': typeof AuthInstallationsRoute
  '/reports': typeof AuthReportsRoute
  '/schedule': typeof AuthScheduleRoute
  '/users': typeof AuthUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/attendance': typeof AuthAttendanceRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/equipment': typeof AuthEquipmentRoute
  '/_auth/forum': typeof AuthForumRoute
  '/_auth/incidents': typeof AuthIncidentsRoute
  '/_auth/installations': typeof AuthInstallationsRoute
  '/_auth/reports': typeof AuthReportsRoute
  '/_auth/schedule': typeof AuthScheduleRoute
  '/_auth/users': typeof AuthUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/attendance'
    | '/dashboard'
    | '/equipment'
    | '/forum'
    | '/incidents'
    | '/installations'
    | '/reports'
    | '/schedule'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/attendance'
    | '/dashboard'
    | '/equipment'
    | '/forum'
    | '/incidents'
    | '/installations'
    | '/reports'
    | '/schedule'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/attendance'
    | '/_auth/dashboard'
    | '/_auth/equipment'
    | '/_auth/forum'
    | '/_auth/incidents'
    | '/_auth/installations'
    | '/_auth/reports'
    | '/_auth/schedule'
    | '/_auth/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/users': {
      id: '/_auth/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthUsersRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/schedule': {
      id: '/_auth/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthScheduleRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports': {
      id: '/_auth/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthReportsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/installations': {
      id: '/_auth/installations'
      path: '/installations'
      fullPath: '/installations'
      preLoaderRoute: typeof AuthInstallationsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/incidents': {
      id: '/_auth/incidents'
      path: '/incidents'
      fullPath: '/incidents'
      preLoaderRoute: typeof AuthIncidentsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/forum': {
      id: '/_auth/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof AuthForumRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/equipment': {
      id: '/_auth/equipment'
      path: '/equipment'
      fullPath: '/equipment'
      preLoaderRoute: typeof AuthEquipmentRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/attendance': {
      id: '/_auth/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AuthAttendanceRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAttendanceRoute: typeof AuthAttendanceRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthEquipmentRoute: typeof AuthEquipmentRoute
  AuthForumRoute: typeof AuthForumRoute
  AuthIncidentsRoute: typeof AuthIncidentsRoute
  AuthInstallationsRoute: typeof AuthInstallationsRoute
  AuthReportsRoute: typeof AuthReportsRoute
  AuthScheduleRoute: typeof AuthScheduleRoute
  AuthUsersRoute: typeof AuthUsersRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAttendanceRoute: AuthAttendanceRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthEquipmentRoute: AuthEquipmentRoute,
  AuthForumRoute: AuthForumRoute,
  AuthIncidentsRoute: AuthIncidentsRoute,
  AuthInstallationsRoute: AuthInstallationsRoute,
  AuthReportsRoute: AuthReportsRoute,
  AuthScheduleRoute: AuthScheduleRoute,
  AuthUsersRoute: AuthUsersRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
